name: Push to chocolatey.org

on:
  push:
    branches:
      - 'master'
    paths:
      - 'tiled.nuspec'
      - 'tools/chocolateyInstall.ps1'
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Chocolatey pack
      run: choco pack
    - name: Chocolatey push
      run: choco push --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
